### ISSUE TITLE
throw error when use it

### ISSUE THREAD

**Issue by yinxin630** [JairusSW/as-fetch#1]
```
/Users/xxx/github/assembly-sript-demo/node_modules/@assemblyscript/loader/umd/index.js:423
    const instance = new WebAssembly.Instance(module, imports);
                     ^

TypeError: WebAssembly.Instance(): Import #2 module="wasi_snapshot_preview1" error: module is not an object or function
    at Object.instantiateSync (/Users/xxx/github/assembly-sript-demo/node_modules/@assemblyscript/loader/umd/index.js:423:22)
    at Object.<anonymous> (/Users/xxx/github/assembly-sript-demo/index.js:8:27)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/xxx/github/assembly-sript-demo/tests/index.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
error Command failed with exit code 1.
```

My code
```js
// index.js
const fs = require('fs');
const loader = require('@assemblyscript/loader');
const FetchImport = require('as-fetch/imports');
const Fetch = new FetchImport();
const imports = {
  ...Fetch.wasmImports,
};
const wasmModule = loader.instantiateSync(
  fs.readFileSync(__dirname + '/build/optimized.wasm'),
  imports,
);
Fetch.wasmExports = wasmModule.exports;
module.exports = wasmModule.exports;
```

```ts
// index.ts
import { fetch } from 'as-fetch';

export function testFetch(): void {
  fetch('https://lok.suisuijiang.com/checkStatus?userId=1', {
    method: 'GET',
    mode: 'no-cors',
    headers: [],
  }).then((response) => {
    const text = response.text();
    console.log('Response: ' + text);
  });
}
```

**Comment by yinxin630** [comment]
Above error is resolved. But i get a new error

```
/Users/xxx/github/assembly-sript-demo/node_modules/wasi/src/index.js:1284
      this.view = new DataView(this.memory.buffer);
                                           ^

TypeError: Cannot read properties of undefined (reading 'buffer')
    at WASI.refreshMemory (/Users/xxx/github/assembly-sript-demo/node_modules/wasi/src/index.js:1284:44)
    at getiovs (/Users/xxx/github/assembly-sript-demo/node_modules/wasi/src/index.js:577:12)
    at /Users/xxx/github/assembly-sript-demo/node_modules/wasi/src/index.js:782:9
    at /Users/xxx/github/assembly-sript-demo/node_modules/wasi/src/index.js:434:12
    at wasm://wasm/d814a782:wasm-function[21]:0x1a33
    at wasm://wasm/d814a782:wasm-function[30]:0x271d
    at wasm://wasm/d814a782:wasm-function[28]:0x2045
    at /Users/xxx/github/assembly-sript-demo/node_modules/as-fetch/imports.js:52:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

It get response success but can't run `callback` function

**Comment by yinxin630** [comment]
Finally. I choose use fetch of javescript host. 😢

**Comment by JairusSW** [comment]
Hey, so sorry about this!
fetch isn't working right now. I'll update it later when I have time
